### ISSUE TITLE
Success email too long 

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/covid19-indicators#3]
@akoebs 
On branch Papermillize. 

I have created the python3 job, but the success email is too long to send according to the API 
```
2020-05-21 03:32:20 PM
Traceback (most recent call last):
2020-05-21 03:32:20 PM
  File "/app/script", line 11, in <module>
2020-05-21 03:32:20 PM
    'success_email_addresses' : ['itadata@lacity.org']})
2020-05-21 03:32:20 PM
  File "/opt/conda/lib/python3.7/site-packages/civis/resources/_resources.py", line 289, in f
2020-05-21 03:32:20 PM
    return self._call_api(verb, url, query, body, iterator=iterator)
2020-05-21 03:32:20 PM
  File "/opt/conda/lib/python3.7/site-packages/civis/base.py", line 119, in _call_api
2020-05-21 03:32:20 PM
    resp = self._make_request(method, path, params, data, **kwargs)
2020-05-21 03:32:20 PM
  File "/opt/conda/lib/python3.7/site-packages/civis/base.py", line 109, in _make_request
2020-05-21 03:32:20 PM
    raise CivisAPIError(response)
2020-05-21 03:32:20 PM
civis.base.CivisAPIError: (400) The given request was not as expected: Validation failed: Success email template is too long (maximum is 262144 characters)
2020-05-21 03:32:21 PM
Failed: The job container failed. Exit code 1
```

**Comment by hunterowens** [comment]
closing in favor of SES
